onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver

# 72-hour cooldown: ignore package versions published less than 3 days ago
minimumReleaseAge: 4320

allowBuilds:
  cpu-features: set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  ssh2: set this to true or false
  unrs-resolver: set this to true or false
