export const OPTIONS = {
  genders: [
    { value: "male", label: "Male" },
    { value: "female", label: "Female" },
    { value: "nonbinary", label: "Non-binary" },
    { value: "other", label: "Other" },
    { value: "prefer_not", label: "Prefer not to say" },
  ],
  universities: [
    { value: "mru", label: "Mount Royal University" },
    { value: "uofc", label: "University of Calgary" },
    { value: "ualberta", label: "University of Alberta" },
    { value: "uleth", label: "University of Lethbridge" },
    { value: "macewan", label: "MacEwan University" },
    { value: "sait", label: "SAIT" },
    { value: "nait", label: "NAIT" },
    { value: "other", label: "Other / Not Listed" },
  ],
  majors: [
    { value: "cs", label: "Computer Science" },
    { value: "se", label: "Software Engineering" },
    { value: "is", label: "Information Systems" },
    { value: "data", label: "Data Science" },
    { value: "cyber", label: "Cybersecurity" },
    { value: "ce", label: "Computer Engineering" },
    { value: "uxui", label: "UX / UI Design" },
    { value: "game", label: "Game Development" },
    { value: "other", label: "Other / Custom" },
  ],
  years: [
    { value: 1, label: "1st" },
    { value: 2, label: "2nd" },
    { value: 3, label: "3rd" },
    { value: 4, label: "4th" },
    { value: 5, label: "4+" },
  ],
  interests: [
    { value: "mobile", label: "Mobile App Development" },
    { value: "web", label: "Web Development" },
    { value: "data", label: "Data Science and ML" },
    { value: "ux", label: "UX / UI Design" },
    { value: "game", label: "Game Development" },
  ],
  dietary: [
    { value: "vegetarian", label: "Vegetarian" },
    { value: "vegan", label: "Vegan" },
    { value: "halal", label: "Halal" },
    { value: "kosher", label: "Kosher" },
    { value: "gluten", label: "Gluten-free" },
    { value: "nuts", label: "Peanuts / Tree-nuts allergy" },
    { value: "other", label: "Other" },
  ],
  heardFrom: [
    { value: "poster", label: "Poster" },
    { value: "friend", label: "Friend / Classmate" },
    { value: "social", label: "Social Media" },
    { value: "prof", label: "Professor / Course Announcement" },
    { value: "other", label: "Other" },
  ],
};
